// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTE0YWQLkJbIprc6D--YgURGGhFhrtxc0',
    appId: '1:986982379072:web:00cfdbbb5e88facc6139a5',
    messagingSenderId: '986982379072',
    projectId: 'plurality-ai',
    authDomain: 'plurality-ai.firebaseapp.com',
    storageBucket: 'plurality-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfzU7cxzkmHCKLM7TNpJuPaykqdEV77go',
    appId: '1:986982379072:android:fd28cb76770b75906139a5',
    messagingSenderId: '986982379072',
    projectId: 'plurality-ai',
    storageBucket: 'plurality-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZE0-3J0YbZXiDzSd32J10qkq80ILwxLU',
    appId: '1:986982379072:ios:b4b2ccb9e35dee226139a5',
    messagingSenderId: '986982379072',
    projectId: 'plurality-ai',
    storageBucket: 'plurality-ai.firebasestorage.app',
    iosBundleId: 'com.example.plurality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZE0-3J0YbZXiDzSd32J10qkq80ILwxLU',
    appId: '1:986982379072:ios:b4b2ccb9e35dee226139a5',
    messagingSenderId: '986982379072',
    projectId: 'plurality-ai',
    storageBucket: 'plurality-ai.firebasestorage.app',
    iosBundleId: 'com.example.plurality',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTE0YWQLkJbIprc6D--YgURGGhFhrtxc0',
    appId: '1:986982379072:web:dcdf7f44ac886ca06139a5',
    messagingSenderId: '986982379072',
    projectId: 'plurality-ai',
    authDomain: 'plurality-ai.firebaseapp.com',
    storageBucket: 'plurality-ai.firebasestorage.app',
  );

}