// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:plurality/utils/types.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AttachmentAdapter());
    registerAdapter(ClientLockAdapter());
    registerAdapter(ContentImageURLAdapter());
    registerAdapter(ContentPartAdapter());
    registerAdapter(ConversationAdapter());
    registerAdapter(FunctionCallDataAdapter());
    registerAdapter(MessageAdapter());
    registerAdapter(MiniAppAdapter());
    registerAdapter(MiniAppInputAdapter());
    registerAdapter(ModelAdapter());
    registerAdapter(ModelSelectedAdapter());
    registerAdapter(ToolCallAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AttachmentAdapter());
    registerAdapter(ClientLockAdapter());
    registerAdapter(ContentImageURLAdapter());
    registerAdapter(ContentPartAdapter());
    registerAdapter(ConversationAdapter());
    registerAdapter(FunctionCallDataAdapter());
    registerAdapter(MessageAdapter());
    registerAdapter(MiniAppAdapter());
    registerAdapter(MiniAppInputAdapter());
    registerAdapter(ModelAdapter());
    registerAdapter(ModelSelectedAdapter());
    registerAdapter(ToolCallAdapter());
  }
}
